function PRpoly = getPRpoly(bet, ka, d, alph, Kx, ...
                            omeg, zet, mvs, ...
                            a0, a1)

% Actuator parameters: bet, ka, d, alph, Kx
% VS parameters: omeg, zet, mvs
% Controller parameters: a0, a1

PRpoly = zeros(4,1);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% The following is Mathematica generated - copied and pasted from
% Mathematica output and replaced greek letters such as \[Alpha]
% appropriately. It is otherwise unedited
PRpoly(4) = -((d*Kx*alph^2*omeg*(2*d*Kx*zet + ka*omeg))/(ka*mvs)) ...
            + (d*Kx*alph*omeg^2*((a1*d*Kx*alph)/(a0*mvs) + a0*(-a1 + ...
            alph + bet + 2*zet*omeg)))/ka;
PRpoly(3) = -((d*Kx*alph*(alph + 2*zet*omeg))/mvs) + (d*Kx*...
            alph*omeg^2*(alph + bet + 2*zet*omeg))/ka - (...
            alph*omeg*(2*d*Kx*zet + ka*omeg)*(a0 - a1^2 + (d*Kx*...
            alph)/(a0*mvs) + a1*(alph + bet + ...
            2*zet*omeg)))/ka + ((d*Kx*alph)/ka + ...
            omeg*(2*alph*zet + ...
            omeg))*((a1*d*Kx*alph)/(a0*mvs) + a0*(-a1 + alph + ...
            bet + 2*zet*omeg));
PRpoly(2) = (a1*d*Kx*alph)/(a0*mvs) - (alph*omeg*(2*d*Kx*zet + ...
            ka*omeg))/ka + a0*(-a1 + alph + bet + 2*zet*omeg) ...
            + (alph + bet + 2*zet*omeg)*((d*Kx*alph)/ka + ...
            omeg*(2*alph*zet + omeg)) + (-alph - 2*zet*...
            omeg)*(a0 - a1^2 + (d*Kx*alph)/(a0*mvs) + a1*(alph + ...
            bet + 2*zet*omeg));
PRpoly(1) = bet;
PRpoly = PRpoly.*[1;-1;1;-1];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%