function PRpoly = getPRpoly(bet, ka, d, alph, KF, ...
                            omeg, zet, mvs, ...
                            a0, a1)

% Actuator parameters: bet, ka, d, alph, KF
% VS parameters: omeg, zet, mvs
% Controller parameters: a0, a1

PRpoly = zeros(4,1);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% The following is Mathematica generated - copied and pasted from
% Mathematica output and replaced greek letters such as alph
% appropriately. It is otherwise unedited
PRpoly(4) = -((a0*ka*alph*(d*KF*alph + bet)*(2*a0*zet*omeg + ...
            a1*omeg^2))/(mvs*(d*KF + bet))) + a0*omeg^2*((a0*ka*(...
            alph + bet))/(mvs*(d*KF + bet)) + a1*alph*(d*KF*...
            alph + bet) - d*KF*alph^2*(alph - 2*zet*omeg) ...
            - alph*bet*(alph - 2*zet*omeg));
PRpoly(3) = -((a0*ka*alph*(d*KF*alph + bet)*(a1 + ...
            2*zet*omeg))/(mvs*(d*KF + bet))) + a0*omeg^2*(a1 + ...
            bet + 2*zet*omeg) + (alph^2 - d*KF*alph^2 - ...
            (a0*ka)/(mvs*(d*KF + bet)) - a1*(alph + bet) - ...
            2*alph*zet*omeg - 2*bet*zet*omeg)*(2*a0*...
            zet*omeg + a1*omeg^2) + (a0 + omeg*(2*a1*zet + ...
            omeg))*((a0*ka*(alph + bet))/(mvs*(d*KF + bet)) + a1*...
            alph*(d*KF*alph + bet) - d*KF*alph^2*(alph - 2*...
            zet*omeg) - alph*bet*(alph - 2*zet*omeg));
PRpoly(2) = (a0*ka*(alph + bet))/(mvs*(d*KF + bet)) + ...
            a1*alph*(d*KF*alph + bet) - 2*a0*zet*omeg - a1*...
            omeg^2 - d*KF*alph^2*(alph - 2*zet*omeg) - ...
            alph*bet*(alph - 2*zet*omeg) + (-a1 - 2*zet*...
            omeg)*(-alph^2 + d*KF*alph^2 + (a0*ka)/(mvs*(d*KF + ...
            bet)) + a1*(alph + bet) + 2*alph*zet*omeg + ...
            2*bet*zet*omeg) + (a1 + bet + 2*zet*omeg)*(a0 ...
            + omeg*(2*a1*zet + omeg));
PRpoly(1) = bet;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%